#!/usr/bin/env ruby
require "rubygems"
require 'irb'

module IRB # :nodoc:
  def self.start_session(binding)
    unless @__initialized
      args = ARGV
      ARGV.replace(ARGV.dup)
      IRB.setup(nil)
      ARGV.replace(args)
      @__initialized = true
    end

    workspace = WorkSpace.new(binding)

    irb = Irb.new(workspace)

    @CONF[:IRB_RC].call(irb.context) if @CONF[:IRB_RC]
    @CONF[:MAIN_CONTEXT] = irb.context

    catch(:IRB_EXIT) do
      irb.eval_input
    end
  end
end

SERVER_ROOT = Dir.pwd
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../../Gemfile', __FILE__)
require 'bundler/setup' if File.exists?(ENV['BUNDLE_GEMFILE'])

$0 = "Taazoo App: Feeds"



AUTO_LOAD_PATHS = [
  "lib", "app/controllers", "app/models"
]


$LOAD_PATH.unshift( File.join( Dir.pwd, 'config' ) )


require 'boot'

$stderr.puts " ,-------------------------------------"
$stderr.puts "|        Entering Console              "
$stderr.puts " `-------------------------------------"

IRB.start_session(binding)
